### ISSUE TITLE
 Description Cut

### ISSUE THREAD

**Issue by weberdepaulai12** [leogregianin/ofx-reader#10]
In the <memo> line, when there is no completion tag </ memo>, a current function cuts a description.

**Applied correction:**
`function TOFXReader.InfLine ( sLine : string ): string;
var
	iTemp : integer;
begin
	Result := '';
	sLine := Trim(sLine);
	if FindString('>', sLine) then
	begin
		sLine := Trim(sLine);
		iTemp := Pos('>', sLine);
		if pos('</', sLine) > 0 then
			 Result := copy(sLine, iTemp+1, pos('</', sLine)-iTemp-1)
		else
			// permite ler a linha toda quando não há a conclusão do </ na mesma linha
			// allows you to read the whole line when there is no completion of </ on the same line
			Result := copy(sLine, iTemp+1, length(sLine));
			// desativado em 07/09/2017 - weberdepaula@gmail.com
			// disabled on 09/07/2017 - weberdepaula@gmail.com
			// Result := copy(sLine, iTemp+1, iTemp-1); //
	end;
end;`

**Comment by leogregianin** [comment]
Fiz this, thanks.
